"""Validated scientific evidence context for GENESIS claim gates.

This module separates *raw run metadata* from evidence that was generated by
CodonTrace or loaded through a validator.  User metadata may describe or point
to artifacts, but high-level scientific claim flags must be derived from the
objects carried here, not from caller-provided strings or booleans.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from typing import Any

from codontrace._types import JsonValue
from codontrace.genesis.causal_validation import InterventionResult, PredictiveProbeResult
from codontrace.genesis.contribution_ledger import ContributionLedger
from codontrace.genesis.statistical_protocol import OEEClaimThresholds, OEEMetricsReport


def _unique_digest_tuple(values: Iterable[str]) -> tuple[str, ...]:
    return tuple(sorted({str(value) for value in values if str(value)}))


def _object_digest(value: object) -> str:
    """Return an object's digest string when it exposes a digest attribute/method."""

    digest = getattr(value, "digest", None)
    resolved = digest() if callable(digest) else digest
    return str(resolved or "")


@dataclass(frozen=True, slots=True)
class EvidenceValidationContext:
    """Validated artifacts available to :class:`ScientificClaimGate`.

    The engine never derives high-level scientific evidence flags directly from
    ``GenesisExperimentSpec.metadata``.  A digest string in metadata is only a
    pointer.  It becomes evidence only after a caller loads or generates the
    corresponding object and places it in this context, or after an importer
    records the digest in ``validated_digests`` alongside object-derived fields.
    """

    intervention_results: tuple[InterventionResult, ...] = ()
    oee_reports: tuple[OEEMetricsReport, ...] = ()
    predictive_probe_results: tuple[PredictiveProbeResult, ...] = ()
    semantic_proxy_reports: tuple[object, ...] = ()
    contribution_ledgers: tuple[ContributionLedger, ...] = ()
    validated_digests: tuple[str, ...] = ()
    intervention_protocol_digests: tuple[str, ...] = ()
    paired_seed_protocol_digests: tuple[str, ...] = ()
    replay_capture_digests: tuple[str, ...] = ()
    validated_evidence_flags: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        object.__setattr__(self, "intervention_results", tuple(self.intervention_results))
        object.__setattr__(self, "oee_reports", tuple(self.oee_reports))
        object.__setattr__(self, "predictive_probe_results", tuple(self.predictive_probe_results))
        object.__setattr__(self, "semantic_proxy_reports", tuple(self.semantic_proxy_reports))
        object.__setattr__(self, "contribution_ledgers", tuple(self.contribution_ledgers))
        object.__setattr__(self, "validated_digests", _unique_digest_tuple(self.validated_digests))
        object.__setattr__(
            self,
            "intervention_protocol_digests",
            _unique_digest_tuple(self.intervention_protocol_digests),
        )
        object.__setattr__(
            self,
            "paired_seed_protocol_digests",
            _unique_digest_tuple(self.paired_seed_protocol_digests),
        )
        object.__setattr__(
            self,
            "replay_capture_digests",
            _unique_digest_tuple(self.replay_capture_digests),
        )
        object.__setattr__(
            self,
            "validated_evidence_flags",
            tuple(sorted({str(value) for value in self.validated_evidence_flags if str(value)})),
        )

    @property
    def artifact_digests(self) -> tuple[str, ...]:
        """Digest set derived from validated objects and imported artifacts."""

        values: list[str] = [*self.validated_digests]
        values.extend(result.digest for result in self.intervention_results)
        values.extend(report.digest for report in self.oee_reports)
        values.extend(result.digest for result in self.predictive_probe_results)
        values.extend(ledger.digest for ledger in self.contribution_ledgers)
        values.extend(self.intervention_protocol_digests)
        values.extend(self.paired_seed_protocol_digests)
        values.extend(self.replay_capture_digests)
        values.extend(
            value
            for value in (_object_digest(report) for report in self.semantic_proxy_reports)
            if value
        )
        return _unique_digest_tuple(values)

    def has_validated_intervention_result(self) -> bool:
        return any(
            result.evidence_level == "intervention_supported"
            for result in self.intervention_results
        )

    def best_intervention_result(self) -> InterventionResult | None:
        for result in self.intervention_results:
            if result.evidence_level == "intervention_supported":
                return result
        return self.intervention_results[0] if self.intervention_results else None

    def has_intervention_protocol_artifact(self) -> bool:
        return bool(self.intervention_protocol_digests)

    def has_paired_seed_protocol_artifact(self) -> bool:
        return bool(self.paired_seed_protocol_digests) or any(
            result.paired_seed_count > 0 for result in self.intervention_results
        )

    def has_oee_candidate_report(self) -> bool:
        return any(report.claim_level == "oee_candidate" for report in self.oee_reports)

    def best_oee_report(self) -> OEEMetricsReport | None:
        for report in self.oee_reports:
            if report.claim_level == "oee_candidate":
                return report
        return self.oee_reports[0] if self.oee_reports else None

    def has_predictive_probe_artifact(self) -> bool:
        return bool(self.predictive_probe_results)

    def has_semantic_proxy_artifact(self) -> bool:
        return bool(self.semantic_proxy_reports)

    def scientific_validation_protocol_executed(self) -> bool:
        """True only when validated protocol artifacts are present."""

        return (
            self.has_predictive_probe_artifact()
            or (
                self.has_validated_intervention_result()
                and self.has_intervention_protocol_artifact()
            )
            or self.has_oee_candidate_report()
            or self.has_semantic_proxy_artifact()
            or (bool(self.validated_evidence_flags) and bool(self.artifact_digests))
        )

    def validated_evidence_flag_map(self) -> dict[str, bool]:
        """Evidence flags supplied by a validated artifact loader, never raw metadata.

        These flags are only surfaced when at least one artifact digest and one replay
        capture digest are present. That keeps the path evidence-backed and prevents
        caller metadata from unlocking Phase 2 claims by itself.
        """

        if not self.validated_evidence_flags or not self.artifact_digests:
            return {}
        flags = {name: True for name in self.validated_evidence_flags}
        if self.artifact_digests:
            flags.setdefault("artifact_digest", True)
        if self.replay_capture_digests:
            flags.setdefault("replay_verification", True)
            flags.setdefault("replay_capture", True)
        return flags

    def intervention_evidence_flags(self) -> dict[str, bool]:
        result = self.best_intervention_result()
        if result is None:
            return {
                "intervention_result_artifact": False,
                "intervention_result_digest": False,
                "baseline_digest": False,
                "treatment_digest": False,
                "intervention_protocol_digest": False,
                "effect_size": False,
                "paired_seed_protocol_digest": False,
                "claim_gate_decision_digest": False,
            }
        has_result = result.evidence_level == "intervention_supported"
        return {
            "intervention_result_artifact": has_result,
            "intervention_result_digest": has_result and bool(result.digest),
            "baseline_digest": bool(result.baseline_digest),
            "treatment_digest": bool(result.treatment_digest),
            "intervention_protocol_digest": self.has_intervention_protocol_artifact(),
            "effect_size": result.effect_size is not None,
            "paired_seed_protocol_digest": self.has_paired_seed_protocol_artifact(),
            # The engine will record the ClaimGate-generated decision digest;
            # this is never accepted from user metadata.
            "claim_gate_decision_digest": has_result,
        }

    def oee_evidence_flags(self) -> dict[str, bool]:
        report = self.best_oee_report()
        if report is None:
            return {
                "oee_metrics": False,
                "oee_report_artifact": False,
                "oee_report_digest": False,
                "oee_protocol_executed": False,
                "shadow_run_present": False,
                "min_seed_threshold_met": False,
                "persistence_window_observed": False,
                "confidence_intervals_present": False,
                "stagnation_diversity_status_recorded": False,
                "claim_gate_decision_digest": False,
            }
        thresholds = OEEClaimThresholds()
        has_candidate = report.claim_level == "oee_candidate"
        return {
            "oee_metrics": bool(report.metrics),
            "oee_report_artifact": has_candidate,
            "oee_report_digest": has_candidate and bool(report.digest),
            "oee_protocol_executed": has_candidate,
            "shadow_run_present": report.shadow_adjusted,
            "min_seed_threshold_met": report.seed_count >= thresholds.min_seed_count_research_grade,
            "persistence_window_observed": report.persistence_window_observed
            >= thresholds.min_persistence_window_generations,
            "confidence_intervals_present": bool(report.confidence_intervals),
            "stagnation_diversity_status_recorded": report.stagnation_window >= 0,
            # Generated by ClaimGate during manifest creation, not metadata.
            "claim_gate_decision_digest": has_candidate,
        }

    def predictive_evidence_flags(self) -> dict[str, bool]:
        return {
            "predictive_probe": bool(self.predictive_probe_results),
            "lag_record": bool(self.predictive_probe_results),
            "controls": bool(self.predictive_probe_results),
        }

    def semantic_proxy_evidence_flags(self) -> dict[str, bool]:
        return {
            "semantic_proxy_report": bool(self.semantic_proxy_reports),
            "replay_capture": bool(self.replay_capture_digests),
        }

    def to_dict(self) -> dict[str, JsonValue]:
        return {
            "intervention_result_digests": [result.digest for result in self.intervention_results],
            "oee_report_digests": [report.digest for report in self.oee_reports],
            "predictive_probe_result_digests": [
                result.digest for result in self.predictive_probe_results
            ],
            "semantic_proxy_report_digests": [
                value
                for value in (_object_digest(report) for report in self.semantic_proxy_reports)
                if value
            ],
            "semantic_proxy_report_count": len(self.semantic_proxy_reports),
            "contribution_ledger_digests": [ledger.digest for ledger in self.contribution_ledgers],
            "validated_digests": list(self.validated_digests),
            "intervention_protocol_digests": list(self.intervention_protocol_digests),
            "paired_seed_protocol_digests": list(self.paired_seed_protocol_digests),
            "replay_capture_digests": list(self.replay_capture_digests),
            "validated_evidence_flags": list(self.validated_evidence_flags),
        }


@dataclass(frozen=True, slots=True)
class EvidenceArtifactRegistry:
    """Small immutable holder for externally validated artifact digests."""

    validated_digests: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        object.__setattr__(self, "validated_digests", _unique_digest_tuple(self.validated_digests))

    def contains(self, digest: str) -> bool:
        return digest in self.validated_digests

    def to_context(self, **kwargs: Any) -> EvidenceValidationContext:
        return EvidenceValidationContext(validated_digests=self.validated_digests, **kwargs)
