import type { Lang } from "./types";

const en = {
  app: "Genesis Console",
  claim: "Evidence-based hypothesis evaluation",
  jobs: "Runs",
  chat: "Analyst",
  gates: "Gates",
  scripts: "Scripts",
  host: "Host",
  settings: "Settings",
  log: "Live log",
  follow: "Following",
  followOff: "Follow paused",
  jump: "Latest",
  filter: "Filter lines",
  newRun: "New run",
  emptyTitle: "No run on this host yet",
  emptyBody:
    "Start a smoke check or open the two-generation engine check. This console previews runs and evaluates empirical evidence across active protocols.",
  showCheck: "Open the engine check",
  startSmoke: "Start smoke",
  start: "Start",
  pause: "Pause",
  resume: "Resume",
  resumeRemaining: "Resume remaining",
  stop: "Stop",
  remove: "Remove",
  download: "Download archive",
  downloadLog: "Download log",
  openChat: "Open chat",
  cores: "Cores",
  workers: "Workers",
  generations: "Generations",
  seeds: "Seeds",
  preset: "Preset",
  kind: "Kind",
  title: "Title",
  create: "Create",
  cancel: "Cancel",
  engine: "Engine",
  gateKind: "Gate file",
  scriptKind: "Script record",
  requested: "Requested",
  preview: "Preview horizon",
  statusQueued: "Queued",
  statusRunning: "Running",
  statusPausing: "Pausing...",
  statusPaused: "Paused",
  statusResuming: "Resuming...",
  statusStopping: "Stopping...",
  statusStopped: "Stopped",
  statusArchived: "Archived",
  statusFailed: "Failed",
  diag: "Diagnostics not run",
  exploratory: "Exploratory",
  chatEmpty: "This thread is empty. It stays with this run, not with the others.",
  placeholder: "Ask about this run",
  send: "Send",
  searchThreads: "Search threads",
  noThreads: "No threads yet",
  exportThread: "Export thread",
  pin: "Pin",
  unpin: "Unpin",
  clearThread: "Clear",
  suggestions1: "Are the three arms comparable?",
  suggestions2: "Is Red Queen proved on this run?",
  suggestions3: "What did the last lines say?",
  settingsLang: "Language",
  settingsLog: "Log",
  settingsHost: "Workers",
  settingsEngine: "Engine",
  settingsData: "Data on this browser",
  followToggle: "Follow the log unless you scroll up",
  density: "Density",
  comfortable: "Comfortable",
  compact: "Compact",
  english: "English",
  persian: "فارسی",
  exportAll: "Export chats",
  clearChats: "Clear chats",
  hostWait: "Reading this host",
  hostSource: "Read from the machine serving this console",
  browserSource: "Read from the browser. The serving host did not answer.",
  runnerCap: "The engine runner scales workers dynamically up to the host core count.",
  memory: "Memory",
  load: "Load 1m",
  notReported: "Not reported on this OS",
  platform: "Platform",
  recommend: "Suggested workers",
  gatesLead:
    "Twenty-nine registered gates. A row here is a catalog entry, not a pass on this host.",
  previewFile: "Preview file",
  notRun: "Not run here",
  scriptsLead: "Upload a .py file. The text stays in this browser and is not executed.",
  scriptName: "File name",
  scriptNote: "Note",
  addScript: "Add record",
  close: "Close",
  menu: "Menu",
  logPanel: "Log panel",
  identity: "Package identity",
  ceiling: "Claim ceiling",
  ceilingBody: "Research software. A finished preview is an archive slice, not support for a positive result.",
  errorSeeds: "Seeds must be unique whole numbers, zero or greater.",
  errorGen: "Generations must be at least 2. That is the runner rule.",
  errorWorkers: "Workers must be from 1 to 4, and not more than the cores you pin.",
  errorCores: "Pin at least one detected core.",
  errorScript: "Use a single .py file name, without a path.",
  formHint: "Preview writes two generations, then stops. The requested horizon stays on the card.",
  sliceNote: "Preview clock. Not a board measurement.",
  work: "Work",
  evidence: "Evidence",
  machine: "Machine",
  idle: "Idle field",
  field: "Field",
  searchRuns: "Search name, seed, or id",
  filterAll: "All",
  filterRun: "Active",
  filterDone: "Archived",
  filterPause: "Paused",
  filterStop: "Stopped",
  sort: "Sort",
  sortNew: "Newest",
  sortOld: "Oldest",
  sortStatus: "Active first",
  sortName: "Name",
  expandAll: "Expand all",
  collapseAll: "Collapse all",
  restart: "Restart from scratch",
  seedMatrix: "Seeds on the preview clock",
  seedIdle: "Idle",
  seedActive: "Active",
  seedDone: "Done",
  previewScript: "Preview this record",
  temp: "Temperature",
  ram: "Memory",
  model: "Model",
  modelLocal: "Local analyst",
  modelBoard: "Board model",
  modelMissing: "Not mounted on this host",
  runAll: "Preview all 29 gates",
  openGateChat: "Chat for this gate",
  track: "Track",
  trackEngine: "Evolution engine",
  trackReference: "Reference benchmark",
  trackContracts: "Hypothesis gates",
  release: "Installed identity",
  releaseNote: "The version is this install. GitHub is checked at startup and every 24 hours. A git checkout can fast-forward; nothing is pushed. Runs produce empirical archives and evaluate hypothesis evidence across active protocols.",
  releaseCheck: "Check GitHub",
  releaseUpdate: "Update this checkout",
  releaseLatest: "Latest GitHub release",
  releaseUpToDate: "No newer release. This install matches GitHub.",
  releaseAvailable: "A newer release is on GitHub.",
  releaseBehind: "This checkout is behind origin/main.",
  releaseChecking: "Checking GitHub…",
  releaseFailed: "GitHub could not be reached. Nothing was changed.",
  releaseReadOnly: "The check is read-only. Update uses git pull --ff-only and never pushes. A wheel install is not rewritten.",
  releaseConfirm: "Pull origin/main with fast-forward only? Nothing is pushed.",
  releaseDismiss: "Dismiss",
  releaseOpen: "Open the release",
  upload: "Upload .py",
  stored: "Stored in this browser. Not executed.",
  tooBig: "That file is over 200 KB. It was not stored.",
  downloadSuite: "Download results",
  help: "Help",
  helpTitle: "How this console works",
  helpRuns: "Start, Pause, Stop, and Restart act on the preview clock for that run. They do not launch the engine on this machine.",
  helpGates: "Each gate row can start a preview, pause it, stop it, or restart it. A row is a catalog entry plus the latest preview on this browser. It is not a pytest pass.",
  helpScripts: "Upload stores the .py text here. Windows and Linux paths are reduced to the file name. Preview this record walks a clock for that name. The browser never runs the file.",
  helpZip: "Download results packs every registered gate and its latest preview log into one zip. Download archive on a run is that run only: live.log, status.json, execution.json, and hypothesis evaluation.",
  helpHost: "The runner accepts 1 to 4 workers. Temperature appears only when the operating system exposes a sensor. Windows does not report a load average, so that cell stays blank. GitHub is checked at startup and every 24 hours. The query does not push. A clean git checkout can fast-forward. A pip install is left as it is.",
  coresOnline: "cores online",
  noMatch: "No run matches this filter.",
};

const fa: typeof en = {
  app: "کنسول جنسیس",
  claim: "ارزیابی فرضیه مبتنی بر شواهد",
  jobs: "اجراها",
  chat: "تحلیلگر",
  gates: "گیت‌ها",
  scripts: "اسکریپت‌ها",
  host: "میزبان",
  settings: "تنظیمات",
  log: "لاگ زنده",
  follow: "در حال دنبال کردن",
  followOff: "دنبال کردن متوقف است",
  jump: "آخرین خط",
  filter: "صافی خط‌ها",
  newRun: "اجرای تازه",
  emptyTitle: "هنوز اجرایی روی این میزبان نیست",
  emptyBody:
    "یک تست کوتاه یا بررسی موتور را آغاز کنید. این کنسول پیش‌نمایش اجراها و ارزیابی شواهد تجربی پروتکل‌ها را ارائه می‌دهد.",
  showCheck: "بررسی موتور را باز کن",
  startSmoke: "شروع دود",
  start: "شروع",
  pause: "مکث",
  resume: "ادامه",
  resumeRemaining: "ادامهٔ باقی‌مانده",
  stop: "توقف",
  remove: "حذف",
  download: "دریافت بایگانی",
  downloadLog: "دریافت لاگ",
  openChat: "گفتگوی همین اجرا",
  cores: "هسته‌ها",
  workers: "کارگرها",
  generations: "نسل‌ها",
  seeds: "بذرها",
  preset: "پیش‌تنظیم",
  kind: "گونه",
  title: "عنوان",
  create: "بساز",
  cancel: "انصراف",
  engine: "موتور",
  gateKind: "پروندهٔ گیت",
  scriptKind: "رکورد اسکریپت",
  requested: "درخواست‌شده",
  preview: "افق پیش‌نمایش",
  statusQueued: "در صف",
  statusRunning: "در حال اجرا",
  statusPausing: "در حال مکث...",
  statusPaused: "مکث",
  statusResuming: "در حال ادامه‌دادن...",
  statusStopping: "در حال توقف...",
  statusStopped: "متوقف",
  statusArchived: "بایگانی شد",
  statusFailed: "ناموفق",
  diag: "تشخیص‌ها اجرا نشده",
  exploratory: "اکتشافی",
  chatEmpty: "این رشته خالی است و فقط به همین اجرا تعلق دارد.",
  placeholder: "دربارهٔ همین اجرا بپرس",
  send: "بفرست",
  searchThreads: "جستجوی رشته‌ها",
  noThreads: "هنوز رشته‌ای نیست",
  exportThread: "خروجی رشته",
  pin: "سنجاق",
  unpin: "برداشتن سنجاق",
  clearThread: "پاک کردن",
  suggestions1: "سه بازو قابل مقایسه‌اند؟",
  suggestions2: "ملکهٔ سرخ روی این اجرا اثبات شده؟",
  suggestions3: "آخرین خط‌ها چه گفتند؟",
  settingsLang: "زبان",
  settingsLog: "لاگ",
  settingsHost: "کارگرها",
  settingsEngine: "موتور",
  settingsData: "داده روی همین مرورگر",
  followToggle: "لاگ را دنبال کن مگر اینکه به بالا بروی",
  density: "تراکم",
  comfortable: "راحت",
  compact: "فشرده",
  english: "English",
  persian: "فارسی",
  exportAll: "خروجی گفتگوها",
  clearChats: "پاک کردن گفتگوها",
  hostWait: "در حال خواندن این میزبان",
  hostSource: "از دستگاهی که این کنسول را سرو می‌کند خوانده شد",
  browserSource: "از مرورگر خوانده شد. میزبان سرویس پاسخ نداد.",
  runnerCap: "رانر موتور تعداد کارگرها را متناسب با تعداد هسته‌های این میزبان مقیاس می‌دهد.",
  memory: "حافظه",
  load: "بار یک دقیقه",
  notReported: "روی این سیستم‌عامل گزارش نمی‌شود",
  platform: "سکو",
  recommend: "کارگر پیشنهادی",
  gatesLead: "بیست‌ونه گیت ثبت شده. هر ردیف فقط فهرست است، نه قبولی روی این میزبان.",
  previewFile: "پیش‌نمایش پرونده",
  notRun: "اینجا اجرا نشده",
  scriptsLead: "یک پروندهٔ py بارگذاری کنید. متن در همین مرورگر می‌ماند و اجرا نمی‌شود.",
  scriptName: "نام پرونده",
  scriptNote: "یادداشت",
  addScript: "افزودن رکورد",
  close: "بستن",
  menu: "منو",
  logPanel: "پنل لاگ",
  identity: "هویت بسته",
  ceiling: "سقف ادعا",
  ceilingBody: "نرم‌افزار پژوهشی. پایان پیش‌نمایش یک برش بایگانی است، نه پشتیبانی یک نتیجهٔ مثبت.",
  errorSeeds: "بذرها باید عدد صحیح یکتا و نامنفی باشند.",
  errorGen: "نسل‌ها باید حداقل ۲ باشند. این قاعدهٔ رانر است.",
  errorWorkers: "کارگرها از ۱ تا ۴، و نه بیشتر از هسته‌های سنجاق‌شده.",
  errorCores: "حداقل یک هستهٔ شناسایی‌شده را سنجاق کنید.",
  errorScript: "فقط یک نام پروندهٔ py، بدون مسیر.",
  formHint: "پیش‌نمایش دو نسل می‌نویسد و بعد می‌ایستد. افق درخواستی روی کارت می‌ماند.",
  sliceNote: "ساعت پیش‌نمایش. سنجش روی برد نیست.",
  work: "کار",
  evidence: "مدرک",
  machine: "ماشین",
  idle: "میدان خالی",
  field: "میدان",
  searchRuns: "جستجوی نام، بذر یا شناسه",
  filterAll: "همه",
  filterRun: "فعال",
  filterDone: "بایگانی",
  filterPause: "مکث",
  filterStop: "متوقف",
  sort: "چینش",
  sortNew: "تازه‌ترین",
  sortOld: "قدیمی‌ترین",
  sortStatus: "فعال‌ها اول",
  sortName: "نام",
  expandAll: "باز کردن همه",
  collapseAll: "بستن همه",
  restart: "از اول",
  seedMatrix: "بذرها روی ساعت پیش‌نمایش",
  seedIdle: "بیکار",
  seedActive: "فعال",
  seedDone: "تمام",
  previewScript: "پیش‌نمایش همین رکورد",
  temp: "دما",
  ram: "حافظه",
  model: "مدل",
  modelLocal: "تحلیلگر محلی",
  modelBoard: "مدل برد",
  modelMissing: "روی این میزبان سوار نیست",
  runAll: "پیش‌نمایش هر ۲۹ گیت",
  openGateChat: "گفتگوی همین گیت",
  track: "مسیر",
  trackEngine: "موتور تکامل",
  trackReference: "سنجش مرجع",
  trackContracts: "گیت‌های فرضیه",
  release: "هویت نصب‌شده",
  releaseNote: "نسخه، همین نصب است. گیت‌هاب هنگام شروع و هر ۲۴ ساعت بررسی می‌شود. کلون گیت فقط با fast-forward جلو می‌رود و هیچ چیز پوش نمی‌شود. اجراها خروجی‌های تجربی تولید کرده و شواهد فرضیه‌ها را در پروتکل‌های فعال ارزیابی می‌کنند.",
  releaseCheck: "بررسی گیت‌هاب",
  releaseUpdate: "به‌روزرسانی همین کلون",
  releaseLatest: "آخرین رلیز گیت‌هاب",
  releaseUpToDate: "رلیز جدیدتری نیست. این نصب با گیت‌هاب یکی است.",
  releaseAvailable: "رلیز جدیدتری روی گیت‌هاب هست.",
  releaseBehind: "این کلون از origin/main عقب است.",
  releaseChecking: "در حال بررسی گیت‌هاب…",
  releaseFailed: "گیت‌هاب در دسترس نبود. چیزی تغییر نکرد.",
  releaseReadOnly: "بررسی فقط خواندنی است. به‌روزرسانی git pull --ff-only است و پوش نمی‌کند. نصب wheel بازنویسی نمی‌شود.",
  releaseConfirm: "origin/main فقط با fast-forward گرفته شود؟ هیچ چیز پوش نمی‌شود.",
  releaseDismiss: "بستن",
  releaseOpen: "باز کردن رلیز",
  upload: "بارگذاری py",
  stored: "در همین مرورگر ذخیره شد. اجرا نمی‌شود.",
  tooBig: "پرونده بزرگ‌تر از ۲۰۰ کیلوبایت است و ذخیره نشد.",
  downloadSuite: "دریافت نتایج",
  help: "راهنما",
  helpTitle: "این کنسول چطور کار می‌کند",
  helpRuns: "شروع، مکث، توقف و از نو فقط ساعت پیش‌نمایش همان اجرا را کنترل می‌کنند. موتور روی این دستگاه راه نمی‌افتد.",
  helpGates: "هر ردیف گیت را می‌توان پیش‌نمایش کرد، مکث داد، متوقف کرد یا از نو ساخت. ردیف یعنی فهرست به‌علاوهٔ آخرین پیش‌نمایش در همین مرورگر، نه قبولی pytest.",
  helpScripts: "بارگذاری، متن py را همین‌جا نگه می‌دارد. مسیر ویندوز یا لینوکس به نام پرونده تقلیل می‌یابد. پیش‌نمایش همین رکورد فقط ساعت را برای آن نام جلو می‌برد. مرورگر پرونده را اجرا نمی‌کند.",
  helpZip: "دریافت نتایج، هر گیت ثبت‌شده و آخرین لاگ پیش‌نمایشش را در یک زیپ می‌گذارد. دریافت بایگانی فقط همان اجراست: live.log و status.json و execution.json و ارزیابی فرضیه.",
  helpHost: "رانر ۱ تا ۴ کارگر می‌پذیرد. دما فقط وقتی هست که سیستم‌عامل حسگر بدهد. ویندوز میانگین بار را گزارش نمی‌کند و آن خانه خالی می‌ماند. گیت‌هاب هنگام شروع و هر ۲۴ ساعت بررسی می‌شود. پرسش پوش نمی‌کند. کلون تمیز می‌تواند fast-forward شود. نصب pip دست نمی‌خورد.",
  coresOnline: "هسته آماده",
  noMatch: "اجرایی با این صافی جور نیست.",
};

export const copy = { en, fa };

export function t(lang: Lang) {
  return copy[lang];
}
